apiVersion: v1
kind: Service
metadata:
  name: wil-playground
  namespace: dev
spec:
  type: NodePort
  ports:
  - name: http
    nodePort: 8888
    port: 8888
    # targetPort: 8888
  selector:
    app: wil-playground