apiVersion: v1
kind: Service
metadata:
  name: wil-playground-service
  namespace: dev
spec:
  selector:
    app: wil-playground
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8888

apiVersion: v1
kind: Service
metadata:
  labels:
    app: will42-playground
  name: will-service
  namespace: dev
spec:
  type: ClusterIP
  selector:
    app: will42-playground
  ports:
  - name: http
    port: 8888
    protocol: TCP
    targetPort: 8888
  type: LoadBalancer
